#!\bin\bash

file=LF16145_Reens_MSFL
git show HEAD~5:${file}.tex > lookatold.tex
latexdiff lookatold.tex ${file}.tex > diff.tex
cp ${file}.bib diff.bib
cp ${file}.bib diffNotes.bib
pdflatex diff
bibtex diff||true
pdflatex diff
pdflatex diff
open -a Preview diff.pdf