#!\bin\bash
git show HEAD~15:MolecularSpinFlipLoss.tex > lookatold.tex
latexdiff lookatold.tex MolecularSpinFlipLoss.tex > diff.tex
cp MolecularSpinFlipLoss.bib diff.bib
cp MolecularSpinFlipLossNotes.bib diffNotes.bib